PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX tb: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/tbox#>
PREFIX ab: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/abox#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    <{op_uri}> a tb:Operation ;
               tb:hasInput ?attribute ;
               tb:hasAbstract ?operation;
               tb:hasInput ab:data ;
               tb:hasOutput ab:boolean .
    <{last_op}> tb:nextStep <{op_uri}>.
}
WHERE {
    <{dp}> tb:hasDC ?dc .
    ?dc tb:hasPolicy ?policy .
    FILTER (?policy = <{policy_uri}>)
    ?policy a odrl:Privacy ;
            odrl:duty ?duty .
    ?duty odrl:action ?action .
    ?duty odrl:target ?target .
    FILTER NOT EXISTS { ?duty odrl:constraint ?constraint }
    FILTER NOT EXISTS { ?action odrl:refinement ?refinement }
    FILTER EXISTS { ?duty odrl:action ?action }
    FILTER NOT EXISTS { ?duty odrl:action ?otherAction . FILTER(?otherAction != ?action) }
    FILTER NOT EXISTS { ?duty odrl:target ?otherTarget . FILTER(?otherTarget != ?target) }

    BIND( ?action AS ?operation)
    BIND( ?target AS ?attribute)
}