PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX tb: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/tbox#>
PREFIX ab: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/abox#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>

CONSTRUCT {
    <{op_uri}> a tb:Operation ;
               tb:hasInput ?attribute ;
               tb:hasAbstract ?operation;
               tb:hasInput ab:data ;
               tb:hasOutput ab:data .
    <{last_op}> tb:nextStep <{op_uri}>.
    ?new_op_uri a tb:Operation ;
                tb:hasInput ab:data ;
                tb:hasAbstract odrl:Constraint;
                tb:hasInput ?operator ;
                tb:hasInput ?value ;
                tb:hasOutput ab:data .
    <{op_uri}> tb:nextStep ?new_op_uri.
}
WHERE {
    <{dp}> tb:hasDC ?dc .
    ?dc tb:hasPolicy ?policy .
    FILTER (?policy = <{policy_uri}>)
    ?policy a dqv:QualityPolicy ;
            odrl:duty ?duty .
    ?duty odrl:target ?target .
    ?duty odrl:constraint ?constraint .
    ?constraint odrl:leftOperand ?lop ;
                odrl:rightOperand ?rop ;
                odrl:operator ?op .
    BIND( ?lop AS ?operation)
    BIND( ?target AS ?attribute)
    BIND( ?op AS ?operator)
    BIND( ?rop AS ?value)
    BIND(IRI(CONCAT(STR(ab:), STRUUID())) AS ?new_op_uri)
}