PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX tb: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/tbox#>
PREFIX ab: <http://www.semanticweb.org/acraf/ontologies/2024/healthmesh/abox#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    <{op_uri}> a tb:Operation ;
               tb:hasInput ab:data ;
               tb:hasInput ?attribute ;
               tb:hasInput ?operator ;
               tb:hasInput ?value ;
               tb:hasAbstract odrl:Constraint ;
               tb:hasOutput ab:boolean .
    <{last_op}> tb:nextStep <{op_uri}>.
}
WHERE {
    <{dp}> tb:hasDC ?dc .
    ?dc tb:hasPolicy ?policy .
    FILTER (?policy = <{policy_uri}>)
    ?policy a odrl:Policy ;
            odrl:duty ?duty .
    ?duty odrl:target ?target .
    ?duty odrl:constraint ?constraint .
    ?constraint odrl:leftOperand ?lop ;
                odrl:rightOperand ?rop ;
                odrl:operator ?op .
    BIND(?target AS ?attribute)
    BIND(?op AS ?operator)
    BIND(?rop AS ?value)

    BIND(IRI(CONCAT(STR(ab:), STRUUID())) AS ?new_op_uri)
}
